name: traffic-light-detection
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - numpy=1.19.5
    - matplotlib=3.3.4
    - jupyter
    - opencv=4.4.0
    - pillow=7.2.0
    - scikit-learn=0.23.2
    - scikit-image=0.16.2
    - scipy=1.5.4
    - h5py=2.10.0
    - seaborn=0.10.1
    - pandas=1.1.5
    - ffmpeg
    - imageio=2.8.0
    - lxml=4.6.3
    - cython=0.29.21
    - contextlib2
    - protobuf=3.13.0
    - python-tk
    - pip:
        - tensorflow==1.15.5
        - tensorflow-gpu==1.15.5
        - moviepy==1.0.3
        - keras==2.3.1
        - pycocotools-windows
